### PR TITLE
slf4j-api and jvm update

### PR DESCRIPTION
**Pull request by usnasoft**
slf4j-api from 1.7.36 to 2.0.7
jvm from 1.6 to 1.8

I'm sorry, I did so much mess with git I preferred to reset everithing and do it again.
Same changes as before:
- upadate of slf4j-api from 1.7.36 to 2.0.7;
- update of jvm to 1.8;
- logger instantiated by ".class" and not by name
  (e.g.: static Logger logger = LoggerFactory.getLogger(RecordReaper.class); insead of
  static Logger logger = LoggerFactory.getLogger(RecordReaper.class.getName();)
- No String concatenation into log calls

eclipse specific files (.classpath and .settings) depend by eclipse version, so I think that editing them by hand is not feasible without risks; "Maven -> Update Project ..." on the project context menu should do the trick. 
Alternatively, if you prefer, I could remove these files from PR

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]
Thank you! This looks all clean this time.

**Comment by MWingbermuhle** [comment]
@kaikreuzer Could you please make a release (3.5.9?) of this soon? My PR of 1 year ago (#242) was merged but never released.

**Comment by kaikreuzer** [comment]
@usnasoft Could you help on reviewing the two remaining open PRs, so that we can decide what to do with them?
Once they are closed, I will do a new release!

**Comment by kaikreuzer** [comment]
Hey @MWingbermuhle, sorry, it took a while, but now we finally have a new release published: https://github.com/jmdns/jmdns/releases/tag/3.5.9

**Pull request merged**
