### PR TITLE
Fix #194: DNSRecord sb.append already handles "null"

### LINKED ISSUE #194: Superfluous null handling with StringBuilder.append
For some reason null is being handled manually only to produce the same result as append(null)

https://github.com/jmdns/jmdns/blob/d15acaf8ad5f11fc6a1dfa597e3e36803a332dbd/src/main/java/javax/jmdns/impl/DNSRecord.java#L570

### PR DESCRIPTION
**Pull request by melloware**
Fix #194: DNSRecord sb.append already handles "null"

@janossch this was the smallest possible PR for this ticket

### CODE REVIEW

**Comment by janossch** [comment]
@melloware obviously. But imho I added extra small but useful modifications to the same file. I know the other PR has conflicts because a later PR hit the main earlier. I'll resolve that other PR soon, but I don't think this issue is so super urgent to start a second PR for it. If this hits the main before my other PR, it loses its main purpose.

**Comment by melloware** [comment]
I just wasn't sure if yours was being ignore because it tackles too much for what is described in the original ticket?

**Comment by janossch** [comment]
It was reviewed by you as well, wasn't it? I don't see right now any concerns there. But if something will be raised I'm open for conversation. I hope maintainers feel that PR valuable.

**Comment by melloware** [comment]
Yes I have no problem with your PR but i see many others being accepted but not yours.  Not sure the reason. 

Also look at 2 of my other DNSRecord PR's they fix specific bugs and they do it slightly different than you have in your PR.

**Comment by kaikreuzer** [comment]
> Not sure the reason.

No specific reason. Just not handling PRs chronologically, but sometimes doing simpler ones to review earlier due to time constraints.

**Comment by kaikreuzer** [comment]
Can be closed as https://github.com/jmdns/jmdns/pull/292 has been merged already.

**Pull request closed without merging**
