### PR TITLE
Revert "Fixing desugaring issue"

### PR DESCRIPTION
**Pull request by kaikreuzer**
This reverts commit 6d747fb5dd9d36fc781d6dac056881b10585ff9c.

Fixes https://github.com/jmdns/jmdns/issues/211

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@MWingbermuhle, @edgsousa and @HPSudip: Feel free to veto if you think this is a bad idea.

**Comment by edgsousa** [comment]
What about the R8 issue? Is it still relevant?

The concurrent exceptions are most likely because lacking synchronized on the entrylist on the methods add & remove dns entries

**Comment by kaikreuzer** [comment]
> What about the R8 issue? Is it still relevant?

According to https://github.com/jmdns/jmdns/issues/211#issuecomment-799595674, it does not seem to be relevant anymore.

**Comment by kaikreuzer** [comment]
Ok, as nobody casts a veto, we all hope Google has fixed the issue on the Android side, so that it should be fine to revert this change and solve the NPEs and CMEs with it.

**Pull request merged**
