### PR TITLE
Slightly reduced memory usage of the DNSCache

### PR DESCRIPTION
**Pull request by joerg1985**
Use more accurate map implementations and presize the lists inside the 
cache to reduce the memory usage.

### CODE REVIEW

**Comment by joerg1985** [comment]
Here are details to this PR, i am running openHab 3.4 on a Raspi, which is a memory constrained environment.
Sometimes the JmDNSImpl is one of the object with the biggest memory footprint.

image

Most of this is due to the _cache field
image

A significant part of each entry in the cache is the _qualifiedNameMap, which is replaced in this PR.
image

**Comment by joerg1985** [comment]
@kaikreuzer could you have a look at this? thanks in advance

**Comment by kaikreuzer** [comment]
@joerg1985 Interesting change, thank you! It is actually the first time I hear about `EnumMap` - sounds useful indeed.
But will this change have any significant impact? As you showed, the cache size is somehow much bigger than the value it brings. Should we think about any further measures, like e.g. converting the cache to a LRU cache?

**Review by MWingbermuhle — APPROVED** [review]
Good improvements, with not much risk. 

According to the Javadoc of ArrayList, the parameter of the constructor is the initialCapacity, and it will grow the capacity when needed, but this indeed will initially reduce the memory footprint of the cache, but not actually limit it. The only concern here is that growing the capacity will cost performance because of allocation times on constrained environments. If that poses a problem to somebody at some point, he/she can consider filing a PR to make that configurable somewhere.

Using the EnumMap also seems like a good alternative, and will not pose a risk at all. The semantics and behavior of EnumMap and HashMap are identical when using a Enum as key.

**Review by kaikreuzer — APPROVED** [review]
Thanks for the PR, @joerg1985 and thanks for the review @MWingbermuhle!

Let's merge this then and have it as part of the next release.

**Pull request merged**
