### PR TITLE
Run tests on windows, mac, linux

### PR DESCRIPTION
**Pull request by melloware**
on Mac OS

```
JmmDNSTest.testRegisterService:64 We should see the service we just registered:  ==> expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 80, Failures: 5, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by melloware** [comment]
@kaikreuzer looks like Mac they fail on...  are you on a Mac?  cc @janossch

**Comment by kaikreuzer** [comment]
Yes, see https://github.com/jmdns/jmdns/pull/318#issuecomment-2436160001

**Comment by melloware** [comment]
well at least we know why 😄

**Comment by melloware** [comment]
should we disable tests on Mac only for now?

**Comment by janossch** [comment]
Unfortunately not exactly the same results, one is different among the 5 failures:

Mac:
DNSStatefulObjectTest.testWaitAndTimeout

In your result:
JmDNSTest.testTwoMulticastPortsAtOnce

**Comment by janossch** [comment]
@melloware Under JDK8 I've seen similar failures... Maybe that could help to reproduce these failed tests.

**Comment by melloware** [comment]
image

JDK21 is because we need the latest Mockito so all 3 failed.

JDK8 apparently is NOT offered for MacOs on Github Actions

**Comment by melloware** [comment]
looks like the tests consistently fail on Mac but fine on Windows and Linux.

**Comment by janossch** [comment]
Even `mockito-inline` _5.2.0_ is still refer to _1.14.1_ from `byte-buddy` which does not support java 21. 

Only after there release of ASM _9.5_ `byte-buddy` started to support java 21:
https://github.com/raphw/byte-buddy/commit/57e32d779a94f163f2c9f9ee04a276b6588a2cb6

One approach would be to reference this `byte-buddy` version:
```
<dependency>
	<groupId>net.bytebuddy</groupId>
	<artifactId>byte-buddy</artifactId>
	<version>1.14.3</version>
	<scope>test</scope>
</dependency>
```

_Side note:_ `mockito-inline` had been removed, starting from `mockito` _5.3.0_ and in the later versions.
https://github.com/mockito/mockito/releases/tag/v5.3.0

If JmDNS decide to switch to a newer _mockito_ (5+) it would be better to reference `mockito-core` instead of `mockito-inline`.

**Comment by melloware** [comment]
yes we should reference Mockito Core and Add ByteBuddy

**Review by kaikreuzer — APPROVED** [review]
Thanks!

**Pull request merged**
