### PR TITLE
Bug 191 Allow Dots in Instance Names for Subscription

### PR DESCRIPTION
**Pull request by axlsml**
Issue: https://github.com/jmdns/jmdns/issues/191
This is very related to https://github.com/jmdns/jmdns/issues/180 and https://github.com/jmdns/jmdns/pull/179.

The above changes by @mattiasbe fix the issue for **publishing** services However you cannot **subscribe** to such a service because the ServiceInfoImpl.decodeQualifiedNameMapForType() method can't handle the dot in instance names. 

Same reason here, I am quoting @mattiasbe:
> The reason for this requested support is that the European ITxPT public transport standard is using an additional extra field in the instance containing the separator dot.

For example subscribing to this won't work:
* instancename._apc._itxpt_http._tcp.local. :x: (instance should be instancename._apc)

However without the dot, it does:
* instancename_apc._itxpt_http._tcp.local. :heavy_check_mark: (instance should be instancename_apc)

So, in this pull request the decoding implementation is changed to work with the dot. I have removed the decode stuff from ServiceInfoImpl and put it into ServiceTypeDecoder. Also decode-related tests are moved from ServiceInfoTest to ServiceTypeDecoderTest. Plus a lot of tests are added, too.

---

Side note: I think also the decoding of subtypes is improved with this pull request. For example, the following type string was not decoded properly before:
* subtype._sub._apple-mobdev2._tcp.local. :x:

Apparently the previous implementation requires a leading underscore for subtypes. However RFC 6763, part "7.1.  Selective Instance Enumeration (Subtypes)" mentions:
> Subtype strings are not required to begin with an underscore, though
   they often do.  As with the TXT record key/value pairs, the list of
   possible subtypes, if any (including whether some or all begin with
   an underscore) are defined and specified separately for each basic
   service type.

Please, let me know what you think. Cheers! :)

### CODE REVIEW

**Comment by axlsml** [comment]
I also created an issue according to the contribution guidelines: https://github.com/jmdns/jmdns/issues/191

**Comment by axlsml** [comment]
@kaikreuzer please, any feedback here?

Can I do something to let travis-ci pass the build? I don't think its a problem related to those changes, is it?

**Comment by rolfchess** [comment]
The travis-ci build fails because it wants to install java 7, but the installer script expects a version between 9 and 13:

```
install-jdk.sh 2019-05-02

Expected feature release number in range of 9 to 14, but got: 7

The command "~/bin/install-jdk.sh --target "/home/travis/openjdk7" --workspace "/home/travis/.cache/install-jdk" --feature "7" --license "GPL" --cacerts" failed and exited with 3 during .
``` 
I think that is part of the Travis environment and not a problem with the source code. I've built this pull request locally against Java 8 without problems.

@kaikreuzer can you help us out with integrating this pull request?

**Comment by kaikreuzer** [comment]
Hey guys, sorry for having neglected that project over the past year...
Will try to catch up now. Just changed the travis config to use Java 8 instead of Java 7, which should make it work again.
Let me quickly close and reopen this PR to see, if it works.

**Review by kaikreuzer — APPROVED** [review]
Many thanks @axlsml for your thorough analysis, the detailed descriptions and the issue entry with a perfect PR for it 👍 .
Sorry again for having that not processed for such a long time 😞 . I'll do a new JmDNS release in October.
If you have any other bugs/fixes that you'd like to get in, let me know!

**Comment by axlsml** [comment]
@kaikreuzer glad to hear. Thanks for merging! 👍

**Pull request merged**
