### PR TITLE
TEST ONLY - Improving tests

### PR DESCRIPTION
**Pull request by janossch**
- [x] Upgrade to JUnit5. 
- [x] Remove easymock.
- [x] Add logback-classic for tests.
- [x] Make tests 'green'

I wanted to move the below listed files under `javax.jmdns.impl` package, but it needs to be a separate PR (even if they are moved, git cannot preserve their history).
- _DNSStatefulObjectTest.java_
- _JmmDNSTest.java_
- _ServiceInfoTest.java_
- _TextUpdateTest.java_

**No goal:**
- optimize on tests (performance)
- stabilize tests (I can not guarantee there aren't any `flaky` tests)
- remove duplicate tests
- since more or less all `JmDNS` and `JmmDNS` tests are multi-threaded, it was no goal to remove `Thread.sleep()`

### CODE REVIEW

**Comment by melloware** [comment]
+1000

**Comment by janossch** [comment]
@kaikreuzer @melloware @ViToni Please have a look on this! I know it is not ideal to have all these steps in a single PR, but keep in mind that these tests haven't executed (automatically) for a long time in the build.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
The tests have been failing for what seems like years so I think this was vital to do in 1 PR and we need to turn on CI/CD again testing ASAP.

**Comment by janossch** [comment]
@melloware Frankly speaking I don't know, I haven't tried it on MacBook.

**Comment by melloware** [comment]
I have a feeling its no longer an issue and it might not be mac book related just OpenJDK from 4 years ago.

**Comment by melloware** [comment]
@janossch you might want to rebase from main and then run `mvn license:format` to fix any license headers

**Comment by janossch** [comment]
@melloware thx for the notification. I resolved the merge conflicts and I squashed the two commits into one. Tests in the CI build seems surprisingly stable. There were some build attempts during I made the aforementioned modifications and all succeeded. You can find the [latest CI build results with executed tests here](https://github.com/jmdns/jmdns/actions/runs/11308346791/job/31451082010?pr=318).

**Comment by melloware** [comment]
Fantastic!

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@kaikreuzer i think this Pr is critical so we can re enabled tests on CI/CD pipeline.  Can we get this merged?

**Review by kaikreuzer — APPROVED** [review]
Awesome - thanks @janossch!

**Comment by kaikreuzer** [comment]
Running the build, I am still getting 5 failed tests:
```
[ERROR] Failures:
[ERROR]   JmDNSTest.testTwoMulticastPortsAtOnce:379 We did not receive the data in the second socket
[ERROR]   JmmDNSTest.testListMyService:145 We should see the service we just registered:  ==> expected: <true> but was: <false>
[ERROR]   JmmDNSTest.testListenForMyService:163
Wanted but not invoked:
serviceListener.serviceAdded(
    <Capturing argument>
);
-> at javax.jmdns.test.JmmDNSTest.testListenForMyService(JmmDNSTest.java:163)
Actually, there were zero interactions with this mock.

[ERROR]   JmmDNSTest.testListenForMyServiceAndList:189
Wanted but not invoked:
serviceListener.serviceAdded(
    <Capturing argument>
);
-> at javax.jmdns.test.JmmDNSTest.testListenForMyServiceAndList(JmmDNSTest.java:189)
Actually, there were zero interactions with this mock.

[ERROR]   JmmDNSTest.testRegisterService:64 We should see the service we just registered:  ==> expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 80, Failures: 5, Errors: 0, Skipped: 0
```
Is it working for you without issues?

**Comment by melloware** [comment]
i just did a clean checkout from `main` and they all passed

```
C:\dev\melloware\jmdns>mvn --version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: C:\tools\apache-maven-3.9.9
Java version: 17.0.11, vendor: Eclipse Adoptium, runtime: C:\tools\jdk-17.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by janossch** [comment]
Could you please give a try under JDK17? (I know it should run under JDK8, but they are fine in the CI).
BTW I think this is kind of a threading issue in the tests.

**Comment by kaikreuzer** [comment]
I was using JDK17 already.
Luckily, GitHub shows [the same result on macOS](https://github.com/jmdns/jmdns/actions/runs/11505620815/job/32027721211?pr=330), so I am not alone. 😇

**Pull request merged**
