### PR TITLE
Closes #287, added termination and shutdown checks before submitting …

### LINKED ISSUE #287: Crash on Android 14
In rare cases jmDNS crashes on Android 14 devices. I can't reproduce it consistently. But it happens from time to time.

The stacktrace from the crash is:

```
java.util.concurrent.RejectedExecutionException:Taskjava.util.concurrent.FutureTask@dca[Notcompleted]rejectedfromjava.util.concurrent.ThreadPoolExecutor@43a[Terminated,poolsize=0,activethreads=0,queuedtasks=0,completedtasks=185]
atjava.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
atjava.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
atjava.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
atjava.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
atjava.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:705)
atjavax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1324)
atjavax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1461)
atjavax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1583)
atjavax.jmdns.impl.SocketListener.run(SocketListener.java:75)
```

For me it looks like the Threadpool is already terminated because probably the close-method in https://github.com/jmdns/jmdns/blob/main/src/main/java/javax/jmdns/impl/JmDNSImpl.java was called before, which shuts down the executor.

Does anyone else have this problem? In my case in only occurs on Android 14 devices, other Android versions seem to be unaffected.

Thanks in advance for any help or hints.

PullRequest with possible solution: https://github.com/jmdns/jmdns/pull/288/

### PR DESCRIPTION
**Pull request by FFelt**
Fix #287

### CODE REVIEW

**Comment by melloware** [comment]
@FFelt change the comment text above to `Fix #287` and it will link this PR to the ticket.

**Review by melloware — APPROVED** [review]

**Comment by FFelt** [comment]
Hello, I added the link to the issue in the description.

**Comment by melloware** [comment]
Yep now its linked!

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks!
@FFelt May I ask you for your sign-off, so that the [DCO check](https://github.com/jmdns/jmdns/pull/288/checks?check_run_id=29868344239) succeeds?

**Comment by FFelt** [comment]
Hello @kaikreuzer,
I signed off my commits and DCO warnings disappeared.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
