### PR TITLE
Make loggers non-static

### LINKED ISSUE #323: Loggers should be declared non-static
Loggers are declared as `private static final`. This can have impact when having the library deployed on "shared" classpaths. 
It is prefereable to have them `non-static`.
If we care about serialization (which I don't assume) Loggers could be changed to be also `transient`.

For reference see:
- http://slf4j.org/faq.html#declared_static
- https://cwiki.apache.org/confluence/display/COMMONS/Logging+StaticLog

OpenHAB follows such a policy:
- https://www.openhab.org/docs/developer/guidelines.html#f-logging

### PR DESCRIPTION
**Pull request by ViToni**
Some slf4j Loggers were declared as `static`. This has been changed to non-`static`.

Usage of `static` loggers (or other classes in general) can be problematic it environments with shared classpaths and dynamic loading/unloading of JARs.

For reference see:
- http://slf4j.org/faq.html#declared_static
- https://cwiki.apache.org/confluence/display/COMMONS/Logging+StaticLog

Fixes #323.

### CODE REVIEW

**Comment by ViToni** [comment]
@melloware Here is the promised PR regarding the logger. Maybe you'd like to give it a look.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@kaikreuzer i think after this is merged we are good for a release!

**Review by kaikreuzer — APPROVED** [review]
lgtm, thanks.

**Comment by melloware** [comment]
@kaikreuzer any chance we can get that release?

**Comment by kaikreuzer** [comment]
@melloware Here we go: https://github.com/jmdns/jmdns/releases/tag/3.6.0

**Comment by melloware** [comment]
Yes!

**Pull request merged**
